dist: release
release:
  disable: true

builds:
  - id: evcc
    main: main.go
    flags:
      - -tags=release
    ldflags:
      - -X github.com/evcc-io/evcc/server.Version={{ .Tag }} -X github.com/evcc-io/evcc/server.Commit={{ .ShortCommit }} -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - builds:
      - evcc
    replacements:
      darwin: macOS
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - evcc.dist.yaml
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: '{{ .Version }}{{ if eq (len (split .Version ".")) 2 }}.0{{ end }}+{{ .Timestamp }}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore"
      - "^bump"
      - "^docs:"
      - "^test:"

nfpms:
  - id: default
    package_name: evcc
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"

    homepage: https://evcc.io
    description: EV Charge Controller
    maintainer: andig <cpuidle@gmx.de>
    license: MIT
    vendor: evcc.io

    formats:
      - deb

    contents:
      - src: ./packaging/init/evcc.service
        dst: /lib/systemd/system/evcc.service

    scripts:
      postinstall: ./packaging/scripts/postinstall.sh
      preremove: ./packaging/scripts/preremove.sh
      postremove: ./packaging/scripts/postremove.sh
