name: Deploy updated templates

on:
  push:
    branches: [master]
    paths: ["templates/**"]
  workflow_dispatch:

jobs:
  docupdate:
    name: Deploy updated templates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          cache: true
        id: go

      - name: Build docs
        run: make docs

      - name: Deploy to docs repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./templates/docs
          external_repository: evcc-io/docs
          publish_branch: main
          destination_dir: templates
          allow_empty_commit: false
          commit_message: Templates update
        if: ${{ success() }}
